import config from "@/config";
import type { Pricing } from "@/types/pricing";

export const DEFAULT_PRICING: Pricing = {
  plans: [
    { id: "free", name: "Free", amount: config.defaultPlanFreePrice, interval: "month" },
    { id: "hacker", name: "Hacker", amount: config.defaultPlanHackerPrice, interval: "month" },
    { id: "developer", name: "Pro", amount: config.defaultPlanProPrice, interval: "month" },
  ],
  team: {
    costPerMember: config.defaultTeamCostPerMember,
    costPerBuild: config.defaultTeamCostPerBuild,
    maxProjects: config.defaultTeamMaxProjects,
    bandwidthGb: config.defaultTeamBandwidthGb,
    defaultConcurrentBuilds: config.defaultTeamConcurrentBuilds,
    logRetentionDays: config.defaultTeamLogRetentionDays,
  },
  overage: {
    bandwidthPerGb: config.defaultOverageBandwidthPerGb,
    buildMinutesPerMin: config.defaultOverageBuildMinutesPerMin,
  },
  metered: {
    cpuPerGbMonth: 4,
    memoryPerGbMonth: 4,
    storagePerGbMonth: 0.25,
  },
  specs: {
    free: {
      projectLimit: 3,
      webhookEnabled: false,
      customDomain: false,
      deployPrivateOrganization: false,
      autoscalingEnabled: false,
      analytics: false,
      pullRequestPreview: false,
      buildMinutes: 100,
      bandwidth: 10,
      storage: 1,
      concurrentBuilds: 1,
      logRetention: 1,
      supportLevel: "community",
      dbMaxCpu: 0.1,
      dbMaxMemory: 0.25,
      dbMaxStorage: 10,
    },
    hacker: {
      projectLimit: 10,
      webhookEnabled: false,
      customDomain: true,
      deployPrivateOrganization: true,
      autoscalingEnabled: false,
      analytics: false,
      pullRequestPreview: true,
      buildMinutes: 400,
      bandwidth: 100,
      storage: 5,
      concurrentBuilds: 1,
      logRetention: 7,
      supportLevel: "email",
      dbMaxCpu: null,
      dbMaxMemory: null,
      dbMaxStorage: null,
    },
    developer: {
      projectLimit: null,
      webhookEnabled: true,
      customDomain: true,
      deployPrivateOrganization: true,
      autoscalingEnabled: true,
      analytics: true,
      pullRequestPreview: true,
      buildMinutes: 1000,
      bandwidth: 400,
      storage: 20,
      concurrentBuilds: 3,
      logRetention: 14,
      supportLevel: "priority",
      dbMaxCpu: null,
      dbMaxMemory: null,
      dbMaxStorage: null,
    },
    team: {
      projectLimit: null,
      webhookEnabled: true,
      customDomain: true,
      deployPrivateOrganization: true,
      autoscalingEnabled: true,
      analytics: true,
      pullRequestPreview: true,
      buildMinutes: 2000,
      bandwidth: 1000,
      storage: 50,
      concurrentBuilds: 5,
      logRetention: 30,
      supportLevel: "dedicated",
      dbMaxCpu: null,
      dbMaxMemory: null,
      dbMaxStorage: null,
    },
  },
};
