/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ScalingRouteImport } from './routes/scaling'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PasskeyRecoveryRouteImport } from './routes/passkey-recovery'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DomainsRouteImport } from './routes/domains'
import { Route as AddonsRouteImport } from './routes/addons'
import { Route as R2faRouteImport } from './routes/2fa'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScalingIndexRouteImport } from './routes/scaling/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as DomainsIndexRouteImport } from './routes/domains/index'
import { Route as AddonsIndexRouteImport } from './routes/addons/index'
import { Route as WorkspaceNewRouteImport } from './routes/workspace/new'
import { Route as ProjectsNewRouteImport } from './routes/projects/new'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as DomainsBuyRouteImport } from './routes/domains/buy'
import { Route as DomainsDomainNameRouteImport } from './routes/domains/$domainName'
import { Route as AddonsAddonIdRouteImport } from './routes/addons/$addonId'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects/$projectId/index'
import { Route as TeamsTeamNameTransferRouteImport } from './routes/teams/$teamName/transfer'
import { Route as TeamsTeamNameOwnershipTransferRouteImport } from './routes/teams/$teamName/ownership-transfer'
import { Route as TeamsTeamNameInvitationRouteImport } from './routes/teams/$teamName/invitation'
import { Route as ProjectsProjectIdWebAnalyticsRouteImport } from './routes/projects/$projectId/web-analytics'
import { Route as ProjectsProjectIdObservabilityRouteImport } from './routes/projects/$projectId/observability'
import { Route as ProjectsProjectIdLogsRouteImport } from './routes/projects/$projectId/logs'
import { Route as ProjectsProjectIdEnvironmentRouteImport } from './routes/projects/$projectId/environment'
import { Route as ProjectsProjectIdDomainsRouteImport } from './routes/projects/$projectId/domains'
import { Route as ProjectsProjectIdDeploymentHistoryRouteImport } from './routes/projects/$projectId/deployment-history'
import { Route as ProjectsProjectIdConfigurationRouteImport } from './routes/projects/$projectId/configuration'
import { Route as ProjectsProjectIdDomainsIndexRouteImport } from './routes/projects/$projectId/domains/index'
import { Route as ProjectsProjectIdDomainsDomainNameRouteImport } from './routes/projects/$projectId/domains/$domainName'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ScalingRoute = ScalingRouteImport.update({
  id: '/scaling',
  path: '/scaling',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PasskeyRecoveryRoute = PasskeyRecoveryRouteImport.update({
  id: '/passkey-recovery',
  path: '/passkey-recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsRoute = DomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => rootRouteImport,
} as any)
const AddonsRoute = AddonsRouteImport.update({
  id: '/addons',
  path: '/addons',
  getParentRoute: () => rootRouteImport,
} as any)
const R2faRoute = R2faRouteImport.update({
  id: '/2fa',
  path: '/2fa',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScalingIndexRoute = ScalingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ScalingRoute,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const DomainsIndexRoute = DomainsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DomainsRoute,
} as any)
const AddonsIndexRoute = AddonsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AddonsRoute,
} as any)
const WorkspaceNewRoute = WorkspaceNewRouteImport.update({
  id: '/workspace/new',
  path: '/workspace/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const DomainsBuyRoute = DomainsBuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => DomainsRoute,
} as any)
const DomainsDomainNameRoute = DomainsDomainNameRouteImport.update({
  id: '/$domainName',
  path: '/$domainName',
  getParentRoute: () => DomainsRoute,
} as any)
const AddonsAddonIdRoute = AddonsAddonIdRouteImport.update({
  id: '/$addonId',
  path: '/$addonId',
  getParentRoute: () => AddonsRoute,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const TeamsTeamNameTransferRoute = TeamsTeamNameTransferRouteImport.update({
  id: '/teams/$teamName/transfer',
  path: '/teams/$teamName/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamNameOwnershipTransferRoute =
  TeamsTeamNameOwnershipTransferRouteImport.update({
    id: '/teams/$teamName/ownership-transfer',
    path: '/teams/$teamName/ownership-transfer',
    getParentRoute: () => rootRouteImport,
  } as any)
const TeamsTeamNameInvitationRoute = TeamsTeamNameInvitationRouteImport.update({
  id: '/teams/$teamName/invitation',
  path: '/teams/$teamName/invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdWebAnalyticsRoute =
  ProjectsProjectIdWebAnalyticsRouteImport.update({
    id: '/web-analytics',
    path: '/web-analytics',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdObservabilityRoute =
  ProjectsProjectIdObservabilityRouteImport.update({
    id: '/observability',
    path: '/observability',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdLogsRoute = ProjectsProjectIdLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdEnvironmentRoute =
  ProjectsProjectIdEnvironmentRouteImport.update({
    id: '/environment',
    path: '/environment',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdDomainsRoute =
  ProjectsProjectIdDomainsRouteImport.update({
    id: '/domains',
    path: '/domains',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdDeploymentHistoryRoute =
  ProjectsProjectIdDeploymentHistoryRouteImport.update({
    id: '/deployment-history',
    path: '/deployment-history',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdConfigurationRoute =
  ProjectsProjectIdConfigurationRouteImport.update({
    id: '/configuration',
    path: '/configuration',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdDomainsIndexRoute =
  ProjectsProjectIdDomainsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsProjectIdDomainsRoute,
  } as any)
const ProjectsProjectIdDomainsDomainNameRoute =
  ProjectsProjectIdDomainsDomainNameRouteImport.update({
    id: '/$domainName',
    path: '/$domainName',
    getParentRoute: () => ProjectsProjectIdDomainsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/2fa': typeof R2faRoute
  '/addons': typeof AddonsRouteWithChildren
  '/domains': typeof DomainsRouteWithChildren
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/passkey-recovery': typeof PasskeyRecoveryRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/scaling': typeof ScalingRouteWithChildren
  '/signup': typeof SignupRoute
  '/addons/$addonId': typeof AddonsAddonIdRoute
  '/domains/$domainName': typeof DomainsDomainNameRoute
  '/domains/buy': typeof DomainsBuyRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/workspace/new': typeof WorkspaceNewRoute
  '/addons/': typeof AddonsIndexRoute
  '/domains/': typeof DomainsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/scaling/': typeof ScalingIndexRoute
  '/projects/$projectId/configuration': typeof ProjectsProjectIdConfigurationRoute
  '/projects/$projectId/deployment-history': typeof ProjectsProjectIdDeploymentHistoryRoute
  '/projects/$projectId/domains': typeof ProjectsProjectIdDomainsRouteWithChildren
  '/projects/$projectId/environment': typeof ProjectsProjectIdEnvironmentRoute
  '/projects/$projectId/logs': typeof ProjectsProjectIdLogsRoute
  '/projects/$projectId/observability': typeof ProjectsProjectIdObservabilityRoute
  '/projects/$projectId/web-analytics': typeof ProjectsProjectIdWebAnalyticsRoute
  '/teams/$teamName/invitation': typeof TeamsTeamNameInvitationRoute
  '/teams/$teamName/ownership-transfer': typeof TeamsTeamNameOwnershipTransferRoute
  '/teams/$teamName/transfer': typeof TeamsTeamNameTransferRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/domains/$domainName': typeof ProjectsProjectIdDomainsDomainNameRoute
  '/projects/$projectId/domains/': typeof ProjectsProjectIdDomainsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/2fa': typeof R2faRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/passkey-recovery': typeof PasskeyRecoveryRoute
  '/signup': typeof SignupRoute
  '/addons/$addonId': typeof AddonsAddonIdRoute
  '/domains/$domainName': typeof DomainsDomainNameRoute
  '/domains/buy': typeof DomainsBuyRoute
  '/projects/new': typeof ProjectsNewRoute
  '/workspace/new': typeof WorkspaceNewRoute
  '/addons': typeof AddonsIndexRoute
  '/domains': typeof DomainsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/scaling': typeof ScalingIndexRoute
  '/projects/$projectId/configuration': typeof ProjectsProjectIdConfigurationRoute
  '/projects/$projectId/deployment-history': typeof ProjectsProjectIdDeploymentHistoryRoute
  '/projects/$projectId/environment': typeof ProjectsProjectIdEnvironmentRoute
  '/projects/$projectId/logs': typeof ProjectsProjectIdLogsRoute
  '/projects/$projectId/observability': typeof ProjectsProjectIdObservabilityRoute
  '/projects/$projectId/web-analytics': typeof ProjectsProjectIdWebAnalyticsRoute
  '/teams/$teamName/invitation': typeof TeamsTeamNameInvitationRoute
  '/teams/$teamName/ownership-transfer': typeof TeamsTeamNameOwnershipTransferRoute
  '/teams/$teamName/transfer': typeof TeamsTeamNameTransferRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/domains/$domainName': typeof ProjectsProjectIdDomainsDomainNameRoute
  '/projects/$projectId/domains': typeof ProjectsProjectIdDomainsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/2fa': typeof R2faRoute
  '/addons': typeof AddonsRouteWithChildren
  '/domains': typeof DomainsRouteWithChildren
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/passkey-recovery': typeof PasskeyRecoveryRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/scaling': typeof ScalingRouteWithChildren
  '/signup': typeof SignupRoute
  '/addons/$addonId': typeof AddonsAddonIdRoute
  '/domains/$domainName': typeof DomainsDomainNameRoute
  '/domains/buy': typeof DomainsBuyRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/workspace/new': typeof WorkspaceNewRoute
  '/addons/': typeof AddonsIndexRoute
  '/domains/': typeof DomainsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/scaling/': typeof ScalingIndexRoute
  '/projects/$projectId/configuration': typeof ProjectsProjectIdConfigurationRoute
  '/projects/$projectId/deployment-history': typeof ProjectsProjectIdDeploymentHistoryRoute
  '/projects/$projectId/domains': typeof ProjectsProjectIdDomainsRouteWithChildren
  '/projects/$projectId/environment': typeof ProjectsProjectIdEnvironmentRoute
  '/projects/$projectId/logs': typeof ProjectsProjectIdLogsRoute
  '/projects/$projectId/observability': typeof ProjectsProjectIdObservabilityRoute
  '/projects/$projectId/web-analytics': typeof ProjectsProjectIdWebAnalyticsRoute
  '/teams/$teamName/invitation': typeof TeamsTeamNameInvitationRoute
  '/teams/$teamName/ownership-transfer': typeof TeamsTeamNameOwnershipTransferRoute
  '/teams/$teamName/transfer': typeof TeamsTeamNameTransferRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/domains/$domainName': typeof ProjectsProjectIdDomainsDomainNameRoute
  '/projects/$projectId/domains/': typeof ProjectsProjectIdDomainsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/2fa'
    | '/addons'
    | '/domains'
    | '/login'
    | '/overview'
    | '/passkey-recovery'
    | '/projects'
    | '/scaling'
    | '/signup'
    | '/addons/$addonId'
    | '/domains/$domainName'
    | '/domains/buy'
    | '/projects/$projectId'
    | '/projects/new'
    | '/workspace/new'
    | '/addons/'
    | '/domains/'
    | '/projects/'
    | '/scaling/'
    | '/projects/$projectId/configuration'
    | '/projects/$projectId/deployment-history'
    | '/projects/$projectId/domains'
    | '/projects/$projectId/environment'
    | '/projects/$projectId/logs'
    | '/projects/$projectId/observability'
    | '/projects/$projectId/web-analytics'
    | '/teams/$teamName/invitation'
    | '/teams/$teamName/ownership-transfer'
    | '/teams/$teamName/transfer'
    | '/projects/$projectId/'
    | '/projects/$projectId/domains/$domainName'
    | '/projects/$projectId/domains/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/2fa'
    | '/login'
    | '/overview'
    | '/passkey-recovery'
    | '/signup'
    | '/addons/$addonId'
    | '/domains/$domainName'
    | '/domains/buy'
    | '/projects/new'
    | '/workspace/new'
    | '/addons'
    | '/domains'
    | '/projects'
    | '/scaling'
    | '/projects/$projectId/configuration'
    | '/projects/$projectId/deployment-history'
    | '/projects/$projectId/environment'
    | '/projects/$projectId/logs'
    | '/projects/$projectId/observability'
    | '/projects/$projectId/web-analytics'
    | '/teams/$teamName/invitation'
    | '/teams/$teamName/ownership-transfer'
    | '/teams/$teamName/transfer'
    | '/projects/$projectId'
    | '/projects/$projectId/domains/$domainName'
    | '/projects/$projectId/domains'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/2fa'
    | '/addons'
    | '/domains'
    | '/login'
    | '/overview'
    | '/passkey-recovery'
    | '/projects'
    | '/scaling'
    | '/signup'
    | '/addons/$addonId'
    | '/domains/$domainName'
    | '/domains/buy'
    | '/projects/$projectId'
    | '/projects/new'
    | '/workspace/new'
    | '/addons/'
    | '/domains/'
    | '/projects/'
    | '/scaling/'
    | '/projects/$projectId/configuration'
    | '/projects/$projectId/deployment-history'
    | '/projects/$projectId/domains'
    | '/projects/$projectId/environment'
    | '/projects/$projectId/logs'
    | '/projects/$projectId/observability'
    | '/projects/$projectId/web-analytics'
    | '/teams/$teamName/invitation'
    | '/teams/$teamName/ownership-transfer'
    | '/teams/$teamName/transfer'
    | '/projects/$projectId/'
    | '/projects/$projectId/domains/$domainName'
    | '/projects/$projectId/domains/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  R2faRoute: typeof R2faRoute
  AddonsRoute: typeof AddonsRouteWithChildren
  DomainsRoute: typeof DomainsRouteWithChildren
  LoginRoute: typeof LoginRoute
  OverviewRoute: typeof OverviewRoute
  PasskeyRecoveryRoute: typeof PasskeyRecoveryRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ScalingRoute: typeof ScalingRouteWithChildren
  SignupRoute: typeof SignupRoute
  WorkspaceNewRoute: typeof WorkspaceNewRoute
  TeamsTeamNameInvitationRoute: typeof TeamsTeamNameInvitationRoute
  TeamsTeamNameOwnershipTransferRoute: typeof TeamsTeamNameOwnershipTransferRoute
  TeamsTeamNameTransferRoute: typeof TeamsTeamNameTransferRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scaling': {
      id: '/scaling'
      path: '/scaling'
      fullPath: '/scaling'
      preLoaderRoute: typeof ScalingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passkey-recovery': {
      id: '/passkey-recovery'
      path: '/passkey-recovery'
      fullPath: '/passkey-recovery'
      preLoaderRoute: typeof PasskeyRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains': {
      id: '/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof DomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addons': {
      id: '/addons'
      path: '/addons'
      fullPath: '/addons'
      preLoaderRoute: typeof AddonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/2fa': {
      id: '/2fa'
      path: '/2fa'
      fullPath: '/2fa'
      preLoaderRoute: typeof R2faRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scaling/': {
      id: '/scaling/'
      path: '/'
      fullPath: '/scaling/'
      preLoaderRoute: typeof ScalingIndexRouteImport
      parentRoute: typeof ScalingRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/domains/': {
      id: '/domains/'
      path: '/'
      fullPath: '/domains/'
      preLoaderRoute: typeof DomainsIndexRouteImport
      parentRoute: typeof DomainsRoute
    }
    '/addons/': {
      id: '/addons/'
      path: '/'
      fullPath: '/addons/'
      preLoaderRoute: typeof AddonsIndexRouteImport
      parentRoute: typeof AddonsRoute
    }
    '/workspace/new': {
      id: '/workspace/new'
      path: '/workspace/new'
      fullPath: '/workspace/new'
      preLoaderRoute: typeof WorkspaceNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/domains/buy': {
      id: '/domains/buy'
      path: '/buy'
      fullPath: '/domains/buy'
      preLoaderRoute: typeof DomainsBuyRouteImport
      parentRoute: typeof DomainsRoute
    }
    '/domains/$domainName': {
      id: '/domains/$domainName'
      path: '/$domainName'
      fullPath: '/domains/$domainName'
      preLoaderRoute: typeof DomainsDomainNameRouteImport
      parentRoute: typeof DomainsRoute
    }
    '/addons/$addonId': {
      id: '/addons/$addonId'
      path: '/$addonId'
      fullPath: '/addons/$addonId'
      preLoaderRoute: typeof AddonsAddonIdRouteImport
      parentRoute: typeof AddonsRoute
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/teams/$teamName/transfer': {
      id: '/teams/$teamName/transfer'
      path: '/teams/$teamName/transfer'
      fullPath: '/teams/$teamName/transfer'
      preLoaderRoute: typeof TeamsTeamNameTransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamName/ownership-transfer': {
      id: '/teams/$teamName/ownership-transfer'
      path: '/teams/$teamName/ownership-transfer'
      fullPath: '/teams/$teamName/ownership-transfer'
      preLoaderRoute: typeof TeamsTeamNameOwnershipTransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamName/invitation': {
      id: '/teams/$teamName/invitation'
      path: '/teams/$teamName/invitation'
      fullPath: '/teams/$teamName/invitation'
      preLoaderRoute: typeof TeamsTeamNameInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/web-analytics': {
      id: '/projects/$projectId/web-analytics'
      path: '/web-analytics'
      fullPath: '/projects/$projectId/web-analytics'
      preLoaderRoute: typeof ProjectsProjectIdWebAnalyticsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/observability': {
      id: '/projects/$projectId/observability'
      path: '/observability'
      fullPath: '/projects/$projectId/observability'
      preLoaderRoute: typeof ProjectsProjectIdObservabilityRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/logs': {
      id: '/projects/$projectId/logs'
      path: '/logs'
      fullPath: '/projects/$projectId/logs'
      preLoaderRoute: typeof ProjectsProjectIdLogsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/environment': {
      id: '/projects/$projectId/environment'
      path: '/environment'
      fullPath: '/projects/$projectId/environment'
      preLoaderRoute: typeof ProjectsProjectIdEnvironmentRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/domains': {
      id: '/projects/$projectId/domains'
      path: '/domains'
      fullPath: '/projects/$projectId/domains'
      preLoaderRoute: typeof ProjectsProjectIdDomainsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/deployment-history': {
      id: '/projects/$projectId/deployment-history'
      path: '/deployment-history'
      fullPath: '/projects/$projectId/deployment-history'
      preLoaderRoute: typeof ProjectsProjectIdDeploymentHistoryRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/configuration': {
      id: '/projects/$projectId/configuration'
      path: '/configuration'
      fullPath: '/projects/$projectId/configuration'
      preLoaderRoute: typeof ProjectsProjectIdConfigurationRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/domains/': {
      id: '/projects/$projectId/domains/'
      path: '/'
      fullPath: '/projects/$projectId/domains/'
      preLoaderRoute: typeof ProjectsProjectIdDomainsIndexRouteImport
      parentRoute: typeof ProjectsProjectIdDomainsRoute
    }
    '/projects/$projectId/domains/$domainName': {
      id: '/projects/$projectId/domains/$domainName'
      path: '/$domainName'
      fullPath: '/projects/$projectId/domains/$domainName'
      preLoaderRoute: typeof ProjectsProjectIdDomainsDomainNameRouteImport
      parentRoute: typeof ProjectsProjectIdDomainsRoute
    }
  }
}

interface AddonsRouteChildren {
  AddonsAddonIdRoute: typeof AddonsAddonIdRoute
  AddonsIndexRoute: typeof AddonsIndexRoute
}

const AddonsRouteChildren: AddonsRouteChildren = {
  AddonsAddonIdRoute: AddonsAddonIdRoute,
  AddonsIndexRoute: AddonsIndexRoute,
}

const AddonsRouteWithChildren =
  AddonsRoute._addFileChildren(AddonsRouteChildren)

interface DomainsRouteChildren {
  DomainsDomainNameRoute: typeof DomainsDomainNameRoute
  DomainsBuyRoute: typeof DomainsBuyRoute
  DomainsIndexRoute: typeof DomainsIndexRoute
}

const DomainsRouteChildren: DomainsRouteChildren = {
  DomainsDomainNameRoute: DomainsDomainNameRoute,
  DomainsBuyRoute: DomainsBuyRoute,
  DomainsIndexRoute: DomainsIndexRoute,
}

const DomainsRouteWithChildren =
  DomainsRoute._addFileChildren(DomainsRouteChildren)

interface ProjectsProjectIdDomainsRouteChildren {
  ProjectsProjectIdDomainsDomainNameRoute: typeof ProjectsProjectIdDomainsDomainNameRoute
  ProjectsProjectIdDomainsIndexRoute: typeof ProjectsProjectIdDomainsIndexRoute
}

const ProjectsProjectIdDomainsRouteChildren: ProjectsProjectIdDomainsRouteChildren =
  {
    ProjectsProjectIdDomainsDomainNameRoute:
      ProjectsProjectIdDomainsDomainNameRoute,
    ProjectsProjectIdDomainsIndexRoute: ProjectsProjectIdDomainsIndexRoute,
  }

const ProjectsProjectIdDomainsRouteWithChildren =
  ProjectsProjectIdDomainsRoute._addFileChildren(
    ProjectsProjectIdDomainsRouteChildren,
  )

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdConfigurationRoute: typeof ProjectsProjectIdConfigurationRoute
  ProjectsProjectIdDeploymentHistoryRoute: typeof ProjectsProjectIdDeploymentHistoryRoute
  ProjectsProjectIdDomainsRoute: typeof ProjectsProjectIdDomainsRouteWithChildren
  ProjectsProjectIdEnvironmentRoute: typeof ProjectsProjectIdEnvironmentRoute
  ProjectsProjectIdLogsRoute: typeof ProjectsProjectIdLogsRoute
  ProjectsProjectIdObservabilityRoute: typeof ProjectsProjectIdObservabilityRoute
  ProjectsProjectIdWebAnalyticsRoute: typeof ProjectsProjectIdWebAnalyticsRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdConfigurationRoute: ProjectsProjectIdConfigurationRoute,
  ProjectsProjectIdDeploymentHistoryRoute:
    ProjectsProjectIdDeploymentHistoryRoute,
  ProjectsProjectIdDomainsRoute: ProjectsProjectIdDomainsRouteWithChildren,
  ProjectsProjectIdEnvironmentRoute: ProjectsProjectIdEnvironmentRoute,
  ProjectsProjectIdLogsRoute: ProjectsProjectIdLogsRoute,
  ProjectsProjectIdObservabilityRoute: ProjectsProjectIdObservabilityRoute,
  ProjectsProjectIdWebAnalyticsRoute: ProjectsProjectIdWebAnalyticsRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  ProjectsNewRoute: typeof ProjectsNewRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  ProjectsNewRoute: ProjectsNewRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface ScalingRouteChildren {
  ScalingIndexRoute: typeof ScalingIndexRoute
}

const ScalingRouteChildren: ScalingRouteChildren = {
  ScalingIndexRoute: ScalingIndexRoute,
}

const ScalingRouteWithChildren =
  ScalingRoute._addFileChildren(ScalingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  R2faRoute: R2faRoute,
  AddonsRoute: AddonsRouteWithChildren,
  DomainsRoute: DomainsRouteWithChildren,
  LoginRoute: LoginRoute,
  OverviewRoute: OverviewRoute,
  PasskeyRecoveryRoute: PasskeyRecoveryRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  ScalingRoute: ScalingRouteWithChildren,
  SignupRoute: SignupRoute,
  WorkspaceNewRoute: WorkspaceNewRoute,
  TeamsTeamNameInvitationRoute: TeamsTeamNameInvitationRoute,
  TeamsTeamNameOwnershipTransferRoute: TeamsTeamNameOwnershipTransferRoute,
  TeamsTeamNameTransferRoute: TeamsTeamNameTransferRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
